// Code generated by mockery v1.0.0

// @generated

package register

import (
	"context"

	"github.com/stretchr/testify/mock"
)

// MockExchanger is an autogenerated mock type for the Exchanger type
type MockExchanger struct {
	mock.Mock
}

// Exchange provides a mock function with given fields: ctx, basePrice, currency
func (_m *MockExchanger) Exchange(ctx context.Context, basePrice float64, currency string) (float64, error) {
	ret := _m.Called(ctx, basePrice, currency)

	var r0 float64
	if rf, ok := ret.Get(0).(func(context.Context, float64, string) float64); ok {
		r0 = rf(ctx, basePrice, currency)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, float64, string) error); ok {
		r1 = rf(ctx, basePrice, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
