// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func initializeDeps() *Fetcher {
	cache := ProvideCache()
	fetcher := ProvideFetcher(cache)
	return fetcher
}
