// Code generated by mockery v1.0.0

// @generated

package rest

import (
	"github.com/PacktPublishing/Hands-On-Dependency-Injection-in-Go/ch06/03_applying/04/data"
	"github.com/stretchr/testify/mock"
)

// MockRegisterModel is an autogenerated mock type for the RegisterModel type
type MockRegisterModel struct {
	mock.Mock
}

// Do provides a mock function with given fields: in
func (_m *MockRegisterModel) Do(in *data.Person) (int, error) {
	ret := _m.Called(in)

	var r0 int
	if rf, ok := ret.Get(0).(func(*data.Person) int); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*data.Person) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
