//+build ignore
// Code above this line should be ignored as it's not part of the example

// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/PacktPublishing/Hands-On-Dependency-Injection-in-Go/ch10/acme/internal/config"
)

// Injectors from wire.go:

func initializeConfig() (*config.Config, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	return configConfig, nil
}
