// Code generated by mockery v1.0.0

// @generated

package rest

import (
	"context"

	"github.com/PacktPublishing/Hands-On-Dependency-Injection-in-Go/ch09/acme/internal/modules/data"
	"github.com/stretchr/testify/mock"
)

// MockRegisterModel is an autogenerated mock type for the RegisterModel type
type MockRegisterModel struct {
	mock.Mock
}

// Do provides a mock function with given fields: ctx, in
func (_m *MockRegisterModel) Do(ctx context.Context, in *data.Person) (int, error) {
	ret := _m.Called(ctx, in)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, *data.Person) int); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *data.Person) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
