// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from injectors.go:

func initializeDeps() *GetPersonHandler {
	db := ProvideDatabase()
	getPersonModel := ProvideModel(db)
	getPersonHandler := ProvideHandler(getPersonModel)
	return getPersonHandler
}
